[package]
name = "jakesky"
authors = ["Jacob Luszcz"]
version = "0.1.0"
edition = "2024"

[dependencies]
again = "0.1"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10"
clap = { version = "4.5", features = ["env"] }
fern = "0.7"
lambda_runtime = "0.13"
log = "0.4"
reqwest = { version = "0.12", features = ["gzip", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.*", features = ["full"] }

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "lambda"
path = "src/lambda.rs"
