[package]
name = "jakesky_rs"
version = "0.1.0"
authors = ["Jacob Luszcz"]
edition = "2018"
default-run = "jakesky"

[[bin]]
name = "bootstrap"
path = "src/lambda.rs"

[[bin]]
name = "jakesky"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.6"
clap = "2.33"
fern = "0.6"
lambda_runtime = "0.4"
log = "0.4"
reqwest = { version = "0.11", features = ["gzip", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.11", features = ["full"] }
