[package]
name = "jakesky_rs"
version = "0.1.0"
authors = ["Jacob Luszcz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = "2.33"
fern = "0.6"
log = "0.4"
