[package]
name = "jakesky_rs"
version = "0.1.0"
authors = ["Jacob Luszcz"]
edition = "2018"

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
chrono-tz = "0.4"
clap = "2.33"
fern = "0.6"
lambda_runtime = "0.3"
log = "0.4"
reqwest = { version = "0.11", features = ["gzip", "json"] }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.6", features = ["full"] }
