[package]
name = "jakesky"
version = "0.1.0"
authors = ["Jacob Luszcz"]
edition = "2021"
default-run = "jakesky"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.8"
clap = { version = "4.0", features = ["env"] }
fern = "0.6"
lambda_runtime = "0.7"
log = "0.4"
reqwest = { version = "0.11", features = ["gzip", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.22", features = ["full"] }

[[bin]]
name = "bootstrap"
path = "src/lambda.rs"

[[bin]]
name = "jakesky"
path = "src/main.rs"
