name: Build and Deploy

on:
  push:
    branches:
      - main

    paths:
      - '.github/workflows/**'
      - 'Cargo**'
      - 'src/**/*.rs'

  pull_request:
    branches:
      - main

env:
  PROJECT: jakesky

jobs:
  build-and-package:
    runs-on: ubuntu-24.04-arm

    permissions:
      id-token: write
      contents: read

    env:
      BUILD_TARGET: aarch64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4

      - name: Update and Configure Rust
        run: |
          sudo apt-get install -y musl-tools
          rustup target add ${{ env.BUILD_TARGET }}
          rustup update
          rustup component add clippy

      - name: Dump Toolchain Info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Build
        run: cargo build --target ${{ env.BUILD_TARGET }}

      - name: Test
        run: cargo test --target ${{ env.BUILD_TARGET }}

      - name: Lint
        run: cargo clippy --target ${{ env.BUILD_TARGET }} -- -D warnings

      - name: Package
        if: github.event_name == 'push'
        run: |
          cargo build --release --target ${{ env.BUILD_TARGET }}
          cp target/${{ env.BUILD_TARGET }}/release/lambda bootstrap
          zip -j ${{ env.PROJECT }}.zip bootstrap

      - name: Upload Package
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ env.PROJECT }}.zip
          retention-days: 1

  deploy:
    needs: build-and-package

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Download Package
        if: github.event_name == 'push'
        uses: actions/download-artifact@v4
        with:
          name: package

      - name: Configure AWS Credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.PROJECT }}.github
          role-session-name: github-deploy
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Deploy Lambda
        if: github.event_name == 'push'
        env:
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        run: aws s3 cp ${{ env.PROJECT }}.zip s3://${AWS_BUCKET}/
