name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'Cargo**'
      - 'src/**/*.rs'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Rust
        run: |
          rustup update
          rustup component add clippy

      - name: Dump Toolchain Info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Lint
        run: cargo clippy -- -D warnings

  deploy:
    needs: build-and-test

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - uses: actions/checkout@v4

      - name: Update Rust
        run: rustup update

      - name: Dump Toolchain Info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Build
        run: cargo build --release --bin bootstrap

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/jakesky.github
          role-session-name: github-deploy
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Deploy Lambda
        env:
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        run: |
          cp target/release/bootstrap .
          zip -j jakesky.zip bootstrap
          aws s3 cp jakesky.zip s3://${AWS_BUCKET}/
